"""init

Revision ID: 1beb6d37aadd
Revises: None
Create Date: 2014-07-23 08:46:35.021350

"""

# revision identifiers, used by Alembic.
revision = '1beb6d37aadd'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
